FROM node:18-slim as builder

RUN apt-get update && apt-get upgrade -y && apt-get autoclean -y && apt-get autoremove -y

WORKDIR /app

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

ENV NPM_CONFIG_LOGLEVEL=warn
COPY . .

RUN corepack enable

RUN pnpm install
RUN chmod +x ./start-mega.sh

# HEALTHCHECK CMD curl --fail http://localhost:8000/health || exit 1
CMD [ "./start-mega.sh" ]



