version: '3.7'
services:
  aidbox-db:
    image: "${PGIMAGE}"
    pull_policy: always
    ports:
      - "${PGHOSTPORT}:5432"
    volumes:
      - "../pgdata:/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  aidbox:
    image: "${AIDBOX_IMAGE}"
    pull_policy: always
    depends_on: ["aidbox-db"]
    links:
      - "aidbox-db:database"
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
      - 9999:9999
    volumes:
      - "../zen-project/:${BOX_PROJECT_GIT_TARGET__PATH}"
    env_file:
      - .env
    environment:
      PGPORT: 5432
      PGHOST: aidbox-db
      BOX_METRICS_PORT: 9999
      BOX_INSTANCE_NAME: adibox
      BOX_METRICS_GRAFANA_URL: host.docker.internal:9000
      BOX_METRICS_GRAFANA_USER: admin
      BOX_METRICS_GRAFANA_PASSWORD: admin
      AIDBOX_ES_URL: http://elasticsearch:9200

  
  prometeus: 
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 9000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    networks:
      - es-net
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  sqs:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://127.0.0.1:9324?Action=ListQueues"]
      interval: 15s
      timeout: 5s
      retries: 60

volumes:
  grafana-data:

networks:
  es-net:
    driver: bridge
  